# Generated by Django 4.2.7 on 2023-11-09 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studcourse', models.IntegerField(verbose_name='Курс')),
                ('studgroup', models.IntegerField(verbose_name='Номер группы')),
                ('week', models.CharField(choices=[('chisl', 'Числитель'), ('znam', 'Знаменатель')], max_length=12, verbose_name='Неделя')),
                ('day', models.CharField(max_length=20, verbose_name='День недели')),
                ('time_start', models.TimeField(verbose_name='Время начала')),
                ('time_end', models.TimeField(verbose_name='Время завершения')),
                ('lesson', models.CharField(max_length=40, verbose_name='Название дисциплины')),
                ('lesson_type', models.CharField(max_length=10, verbose_name='Тип занятия')),
                ('teacher', models.CharField(max_length=100, verbose_name='Преподаватель')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID пользователя')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='Псевдоним пользователя')),
                ('full_name', models.CharField(blank=True, max_length=50, verbose_name='Имя пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('studnum', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер студенческого билета')),
                ('studname', models.CharField(max_length=70, verbose_name='ФИО')),
                ('studgroup', models.IntegerField(verbose_name='Номер группы')),
                ('studyear', models.IntegerField(verbose_name='Год рождения')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.user', verbose_name='ID пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата подачи заявления')),
                ('destination', models.CharField(max_length=50, verbose_name='Название организации')),
                ('status', models.BooleanField(default=False, verbose_name='Статус выполнения')),
                ('studnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.stud', verbose_name='Номер студенческого билета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.user', verbose_name='ID пользователя')),
            ],
        ),
    ]
