# Generated by Django 4.2.7 on 2023-11-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studnum', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер студенческого билета')),
                ('studname', models.CharField(max_length=50, verbose_name='ФИО')),
                ('studgroup', models.IntegerField(verbose_name='Группа')),
                ('studyear', models.IntegerField(verbose_name='Год рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=30)),
                ('full_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, verbose_name='Дата заявки')),
                ('organisation', models.CharField(max_length=50, verbose_name='Название организации')),
                ('created', models.BooleanField(default=False, verbose_name='Состояние выполнения')),
                ('studnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.students', verbose_name='Номер студенческого билета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.users', verbose_name='ID пользователя')),
            ],
        ),
    ]
