# Generated by Django 4.2.7 on 2023-11-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studgraph',
            name='cabinet',
            field=models.CharField(default=0, max_length=10, verbose_name='Номер кабинета'),
        ),
    ]
